### ISSUE TITLE
Why not a hard fork?

### ISSUE THREAD

**Issue by maraujop** [anacronw/js-fixtures#1]
Hi there,

I found your fork through a Stackoverflow broken url and I think this should be really a project by itself, so that it can be promoted like that. As a Github fork you don't appear in search results and the visibility of the project is minimum. We are porting some tests from Jasmine to Mocha and using js-fixtures happily, thanks. 

One little detail, I would state very clear the differences between the API in the top part of the README. Something like:

`readFixtures` is now `fixtures.read()`
`setFixtures` is now `fixtures.set()`

Cheers,
Miguel

**Comment by anacronw** [comment]
great to know someone found this useful!  I made it so that I could migrate from Jasmine to Mocha also.

Thanks for all the comments, I clarified the readme and fixed my stackoverflow link ;)

I kept it as a fork because I want to attribute it back to the original authors.  I didn't know that about search results etc.. however.

**Comment by maraujop** [comment]
Yes, I bet more people are looking or have looked for something like this.

I found it because I thought you maybe turned your hard fork into a soft fork, lucky me! 

I understand you want to attribute the original authors, but in my opinion this is the case where it's legit to hard fork. You can always ask the favor or those original authors explaining your reasons for hard forking and put in your README where you come from and kudos them. 

BTW, why installing this as a node package, it's enough with including the javascript file in the HTML runner, right?

Thanks again for the fork! cheers,
Miguel

**Comment by anacronw** [comment]
you may be right, perhaps I'll hard fork a little later

packaging as a node package helps me grab the development dependencies (chai/mocha) for the tests in the actual library.  Technically, I didn't have to `npm publish` even if I wanted to use `npm install`, but I found it convenient for myself. 

You're right, its technically not a node project since its strictly-browser based but couldn't find any guidelines against that.  I eventually published because chai-jquery is also published and because all the cool kids did it :)

**Comment by maraujop** [comment]
> you may be right, perhaps I'll hard fork a little later

Food for thought.

> You're right, its technically not a node project since its strictly-browser based but couldn't find any guidelines against that. I eventually published because chai-jquery is also published and because all the cool kids did it :)

I see, I guess I'm not in the trend :)
