### ISSUE TITLE
Documentation improvement on loading fixture

### ISSUE THREAD

**Issue by mech** [anacronw/js-fixtures#21]
It seems to be fixtures.load will make the iframe to be `null` on the document unless you wait for it. Meaning to say it is a bit like async. With mocha, I have to do this in order to have iframe's document loaded.

```
beforeEach(function(done) {
  fixtures.load('index.html', function() {
    // I needed to tell mocha it has been loaded
    done();
  });
});
```

Maybe the document can improve or is my understanding of fixtures loading wrong :(

Using Karma, mocha, Rails on my setup FYI.

**Comment by anacronw** [comment]
Technically, loading it via `fixtures.load('index.html')` will load the file synchronously and return.  The asynchronous loading was only added for a particular edge case so that some javascript could load in `<head>` before returning.

Either method shouldn't have an empty fixtures.body().

Perhaps its the content of index.html that you're using?  I did not actually design it such that an entire html document  (`<head>`, `<body>` and all)  to be loaded through this mechanism, only a snippet of it that you wish to test that you'd like in the document body.  Same functionality I believe as jasmine-jquery.

As an aside, I think it would be pretty neat to do that...I do have some plans to do a major refactor to support script loading, document loading, etc. to be in separate methods.  The limitation right now is that it generally only loads stuff into the iframe's document body, but that shouldn't necessarily stop you from loading scripts through that mechanism.

**Comment by imakewebthings** [comment]
> Perhaps its the content of index.html that you're using? I did not actually design it such that an entire html document (<head>, <body> and all) to be loaded through this mechanism, only a snippet of it that you wish to test that you'd like in the document body. Same functionality I believe as jasmine-jquery.

The big difference is jasmine-jquery uses a sandbox div instead of an iframe. With jasmine-jquery your jQuery and files under test are all loaded together on the page and guaranteed to load before tests are executed (assuming you start the runner in a later script). With your iframe, it forces us to put jquery and file under test inside the fixture and their loading before tests execute isn't guaranteed. Hence your callback addition for `load`. All good so far.

What I'm trying to reconcile is your comment above and the documentation in README, which specifically states that your fixture should include those scripts, then uses `window()` to assign the fixture's jQuery to `$$`:

``` js
var $$;
beforeEach(function(){
  fixtures.load('fixture-with-jquery-and-plugin.html');
  $$ = fixtures.window().jQuery; // access the jquery instance from within the fixtures context
  $$('body').pizzazz();
});
```

The example above (for me at least) errors with $$ being undefined. Given the iframe architecture, I don't know that the callback form of load is an "edge case." It seems to be the only way to do things. Am I missing something?

Thanks for the library. Would love to see a 1.3.2 release with the callback form of load included.

**Comment by anacronw** [comment]
Hi - sorry for the late response.

[load already supports the callback form](https://github.com/badunk/js-fixtures/blob/master/fixtures.js#L34) actually, please give it a try

I do notice there are some inconsistencies with loading javascript in the iframe.  I'm in the process of refactoring to support a couple of use cases/pain points.  I will be packaging it as a 2.0.0 release as it won't be backwards compatible (but I plan to support all existing features).

Thanks
